### ISSUE TITLE
There is a issue in the store page navbar

### ISSUE THREAD

**Issue by Blood-Hound** [Blood-Hound/NewTech---ECOMMERCE#1]
The store.html navbar when replace by the main.html navbar, everything glitches and I've tried everything that had come to my mind, but to no avail it doesnt fix.

**Comment by Dhruv-Kaneriya** [comment]
You want to reuse the navbar of main.html in store.html?

Navbar of main.html
![image](https://user-images.githubusercontent.com/58837188/210045159-a9934a88-c7cc-45a1-addc-a55cb88dbfcd.png)

Navbar of store.html
![image](https://user-images.githubusercontent.com/58837188/210045222-1436b921-671d-47c7-9ed3-0a0be3f31e4a.png)

**Comment by Blood-Hound** [comment]
Exactly what I wanted, and how do I do that exactly?
btw, Thank You. Can you do a pull request?

**Comment by Blood-Hound** [comment]
Fr, Indian people are life savers.
